name: 'AWS SAM Deploy unlimited'
description: 'Deploys AWS SAM Stack'
author: 'Luis Navarro Carter <lnavarrocarter@gmail.com>'
branding:
  icon: 'upload-cloud'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
